# Generated by Django 4.2.8 on 2024-01-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email_name',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='role',
            field=models.CharField(default='user', max_length=8, verbose_name='role'),
        ),
    ]
