# Generated by Django 4.2.8 on 2024-01-03 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_buyer_email_name_buyer_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email_name',
        ),
    ]
