# Generated by Django 4.2.8 on 2024-01-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_buyer_email_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='role',
            field=models.CharField(choices=[('manager', 'менеджер'), ('driver', 'водитель')], default='user', max_length=8, verbose_name='role'),
        ),
    ]
