# Generated by Django 4.2.8 on 2024-01-04 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_buyer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='role',
            field=models.CharField(choices=[('manager', 'manager'), ('driver', 'driver')], default='user', max_length=8, verbose_name='role'),
        ),
    ]
