# Generated by Django 4.2.8 on 2024-01-04 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_buyer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, verbose_name='Логин')),
                ('date_and_time_route_from', models.DateTimeField(verbose_name='Дата и время начала маршрута')),
                ('date_and_time_route_to', models.DateTimeField(verbose_name='Дата и время конца маршрута')),
                ('odometr_from', models.BigIntegerField(verbose_name='Одометр на начало маршрута')),
                ('odometr_to', models.BigIntegerField(verbose_name='Одометр на конец маршрута')),
                ('date_check', models.DateField(verbose_name='Дата оплаты чека')),
                ('sum_check', models.BigIntegerField(verbose_name='Сумма чека за бензин')),
                ('image_check', models.FileField(upload_to='', verbose_name='Фото чека за бензин')),
                ('number_route', models.BigIntegerField(verbose_name='Номер маршрута')),
                ('result_route', models.CharField(max_length=10, verbose_name='Результат прохождения маршрута(Пройден или Не пройден)')),
            ],
            options={
                'verbose_name': 'Отчет водителя',
                'verbose_name_plural': 'Отчеты водителей',
            },
        ),
    ]
