# Generated by Django 4.2.8 on 2024-01-04 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_driver_report_image_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver_report',
            name='image_check',
        ),
    ]
