# Generated by Django 4.2.8 on 2024-01-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_driver_report_image_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_report',
            name='sum_check',
            field=models.FloatField(verbose_name='Сумма чека за бензин'),
        ),
    ]
