# Generated by Django 4.2.8 on 2024-01-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_driver_report_sum_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_report',
            name='image_check',
            field=models.FileField(default='', upload_to='image', verbose_name='Фото чека за бензин'),
        ),
    ]
