# Generated by Django 4.2.8 on 2024-01-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_driver_report_image_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_report',
            name='image_check',
            field=models.ImageField(default='', upload_to='images/', verbose_name='Фото чека за бензин'),
        ),
    ]
