# Generated by Django 4.2.8 on 2024-01-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_route',
            fields=[
                ('number_route', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Номер маршрута')),
                ('number_point', models.CharField(max_length=7, verbose_name='Номер точки')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, verbose_name='Долгота')),
            ],
        ),
        migrations.CreateModel(
            name='catalog_route_url',
            fields=[
                ('number_route', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Номер маршрута')),
                ('url_route', models.URLField(verbose_name='Ссылка на маршрут')),
            ],
        ),
        migrations.CreateModel(
            name='driver_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.BigIntegerField(verbose_name='Номер задачи')),
                ('date_and_time_task', models.DateTimeField(verbose_name='Дата и время задачи')),
                ('phone_manager', models.CharField(max_length=11, verbose_name='Телефон менеджера')),
                ('phone_driver', models.CharField(max_length=11, verbose_name='Телефон водителя')),
                ('date_and_time_route_from', models.DateTimeField(verbose_name='Дата и время начала маршрута')),
                ('date_and_time_route_to', models.DateTimeField(verbose_name='Дата и время конца маршрута')),
                ('odometr_from', models.BigIntegerField(verbose_name='Одометр на начало маршрута')),
                ('odometr_to', models.BigIntegerField(verbose_name='Одометр на конец маршрута')),
                ('date_check', models.DateField(verbose_name='Дата оплаты чека')),
                ('sum_check', models.FloatField(verbose_name='Сумма чека за бензин')),
                ('image_check', models.ImageField(upload_to='images/', verbose_name='Фото чека за бензин')),
                ('number_route', models.BigIntegerField(verbose_name='Номер маршрута')),
                ('result_route', models.CharField(max_length=10, verbose_name='Результат прохождения маршрута(Пройден или Не пройден)')),
            ],
            options={
                'verbose_name': 'Отчет водителя',
                'verbose_name_plural': 'Отчеты водителей',
            },
        ),
    ]
