# Generated by Django 4.2.8 on 2024-01-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catalog_route_url',
            fields=[
                ('number_route', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='Номер маршрута')),
                ('point_1', models.CharField(max_length=20, verbose_name='Точка 1')),
                ('point_2', models.CharField(blank=True, max_length=20, verbose_name='Точка 2')),
                ('point_3', models.CharField(blank=True, max_length=20, verbose_name='Точка 3')),
                ('point_4', models.CharField(blank=True, max_length=20, verbose_name='Точка 4')),
                ('point_5', models.CharField(blank=True, max_length=20, verbose_name='Точка 5')),
                ('point_6', models.CharField(blank=True, max_length=20, verbose_name='Точка 6')),
                ('point_7', models.CharField(blank=True, max_length=20, verbose_name='Точка 7')),
                ('point_8', models.CharField(blank=True, max_length=20, verbose_name='Точка 8')),
                ('point_9', models.CharField(blank=True, max_length=20, verbose_name='Точка 9')),
                ('point_10', models.CharField(blank=True, max_length=20, verbose_name='Точка 10')),
                ('url_route', models.URLField(verbose_name='Ссылка на маршрут')),
            ],
            options={
                'verbose_name': 'URL-адрес',
                'verbose_name_plural': 'URL-адреса',
            },
        ),
        migrations.CreateModel(
            name='driver_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_number', models.BigIntegerField(verbose_name='Номер задачи')),
                ('odometr_from', models.BigIntegerField(verbose_name='Одометр на начало маршрута')),
                ('odometr_to', models.BigIntegerField(verbose_name='Одометр на конец маршрута')),
                ('check_number', models.BigIntegerField(default=0, verbose_name='Номер чека')),
                ('date_check', models.DateField(verbose_name='Дата оплаты чека')),
                ('sum_check', models.FloatField(verbose_name='Сумма чека за бензин')),
                ('image_check', models.ImageField(upload_to='images/', verbose_name='Фото чека за бензин')),
            ],
            options={
                'verbose_name': 'Отчет водителя',
                'verbose_name_plural': 'Отчеты водителей',
            },
        ),
        migrations.CreateModel(
            name='driver_step_route',
            fields=[
                ('task_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер задачи')),
                ('date_and_time_route_from', models.DateTimeField(verbose_name='Дата и время начала маршрута')),
                ('point_1', models.BooleanField(blank=True, default=False, verbose_name='Точка 1')),
                ('point_2', models.BooleanField(blank=True, default=False, verbose_name='Точка 2')),
                ('point_3', models.BooleanField(blank=True, default=False, verbose_name='Точка 3')),
                ('point_4', models.BooleanField(blank=True, default=False, verbose_name='Точка 4')),
                ('point_5', models.BooleanField(blank=True, default=False, verbose_name='Точка 5')),
                ('point_6', models.BooleanField(blank=True, default=False, verbose_name='Точка 6')),
                ('point_7', models.BooleanField(blank=True, default=False, verbose_name='Точка 7')),
                ('point_8', models.BooleanField(blank=True, default=False, verbose_name='Точка 8')),
                ('point_9', models.BooleanField(blank=True, default=False, verbose_name='Точка 9')),
                ('point_10', models.BooleanField(blank=True, default=False, verbose_name='Точка 10')),
                ('date_and_time_route_to', models.DateTimeField(verbose_name='Дата и время конца маршрута')),
            ],
            options={
                'verbose_name': 'Прохождение маршрута',
                'verbose_name_plural': 'Прохождение маршрутов',
            },
        ),
        migrations.CreateModel(
            name='manager_task',
            fields=[
                ('task_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер задачи')),
                ('date_and_time_task', models.DateTimeField(verbose_name='Дата и время задачи')),
                ('phone_manager', models.CharField(max_length=11, verbose_name='Телефон менеджера')),
                ('phone_driver', models.CharField(max_length=11, verbose_name='Телефон водителя')),
                ('number_route', models.CharField(max_length=7, verbose_name='Номер маршрута')),
            ],
            options={
                'verbose_name': 'Задача от менеджера',
                'verbose_name_plural': 'Задачи от менеджера',
            },
        ),
    ]
