# Generated by Django 4.2.8 on 2024-01-08 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='driver_step_route',
            fields=[
                ('task_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер задачи')),
                ('date_and_time_route_from', models.DateTimeField(verbose_name='Дата и время начала маршрута')),
                ('point_1', models.BooleanField(default=False, verbose_name='Точка 1')),
                ('point_2', models.BooleanField(default=False, verbose_name='Точка 2')),
                ('point_3', models.BooleanField(default=False, verbose_name='Точка 3')),
                ('point_4', models.BooleanField(default=False, verbose_name='Точка 4')),
                ('point_5', models.BooleanField(default=False, verbose_name='Точка 5')),
                ('point_6', models.BooleanField(default=False, verbose_name='Точка 6')),
                ('point_7', models.BooleanField(default=False, verbose_name='Точка 7')),
                ('point_8', models.BooleanField(default=False, verbose_name='Точка 8')),
                ('point_9', models.BooleanField(default=False, verbose_name='Точка 9')),
                ('point_10', models.BooleanField(default=False, verbose_name='Точка 10')),
                ('date_and_time_route_to', models.DateTimeField(verbose_name='Дата и время конца маршрута')),
            ],
            options={
                'verbose_name': 'Прохождение маршрута',
                'verbose_name_plural': 'Прохождение маршрутов',
            },
        ),
        migrations.CreateModel(
            name='manager_task',
            fields=[
                ('task_number', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Номер задачи')),
                ('date_and_time_task', models.DateTimeField(auto_now=True, verbose_name='Дата и время задачи')),
                ('phone_manager', models.CharField(max_length=11, verbose_name='Телефон менеджера')),
                ('phone_driver', models.CharField(max_length=11, verbose_name='Телефон водителя')),
                ('number_route', models.BigIntegerField(verbose_name='Номер маршрута')),
            ],
            options={
                'verbose_name': 'Задача от менеджера',
                'verbose_name_plural': 'Задачи от менеджера',
            },
        ),
        migrations.AlterModelOptions(
            name='catalog_route',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
        migrations.AlterModelOptions(
            name='catalog_route_url',
            options={'verbose_name': 'URL-адрес', 'verbose_name_plural': 'URL-адреса'},
        ),
    ]
