# Generated by Django 4.2.8 on 2024-01-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog_route_url',
            name='url_route',
            field=models.URLField(max_length=500, verbose_name='Ссылка на маршрут'),
        ),
    ]
