# Generated by Django 4.2.8 on 2024-01-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_manager_task_date_and_time_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_1',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 1'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_10',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 10'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_2',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 2'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_3',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 3'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_4',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 4'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_5',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 5'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_6',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 6'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_7',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 7'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_8',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 8'),
        ),
        migrations.AlterField(
            model_name='driver_step_route',
            name='point_9',
            field=models.BooleanField(blank=True, default=False, verbose_name='Точка 9'),
        ),
        migrations.AlterField(
            model_name='manager_task',
            name='number_route',
            field=models.CharField(max_length=7, verbose_name='Номер маршрута'),
        ),
    ]
